name: Snake Game

on:
  schedule:
    # Executa a cada 5 horas
    - cron: "0 */5 * * *"

  # Permite executar manualmente pelo GitHub Actions
  workflow_dispatch:

# Permissão necessária para o workflow criar/alterar arquivos no repositório
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Baixa o conteúdo do repositório
      - name: Checkout
        uses: actions/checkout@v4

      # Gera o Snake a partir das contribuições do GitHub
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Leo22LonqueDev
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif

      # Publica os arquivos gerados na branch output
      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
